"""create_all_tables

Revision ID: 067b4a044853
Revises: 13768111b80a
Create Date: 2026-05-03 15:46:58.454717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067b4a044853'
down_revision: Union[str, None] = '13768111b80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dias_anticipacion', sa.JSON(), nullable=False),
    sa.Column('email_agente_activo', sa.Boolean(), nullable=False),
    sa.Column('email_cliente_activo', sa.Boolean(), nullable=False),
    sa.Column('email_agente', sa.String(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password_cifrada', sa.String(), nullable=True),
    sa.Column('smtp_from_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_alertas_id'), 'config_alertas', ['id'], unique=False)
    op.create_table('config_llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('api_key_cifrada', sa.String(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_llm_id'), 'config_llm', ['id'], unique=False)
    op.create_table('config_presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('presupuesto_mensual_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('alerta_porcentaje', sa.Integer(), nullable=False),
    sa.Column('alerta_activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_presupuestos_id'), 'config_presupuestos', ['id'], unique=False)
    op.create_index(op.f('ix_config_presupuestos_proveedor'), 'config_presupuestos', ['proveedor'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rfc', sa.String(), nullable=True),
    sa.Column('curp', sa.String(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_agente_id'), 'clientes', ['agente_id'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_rfc'), 'clientes', ['rfc'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('operacion', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('costo_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_id'), 'llm_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_operacion'), 'llm_call_logs', ['operacion'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_proveedor'), 'llm_call_logs', ['proveedor'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_usuario_id'), 'llm_call_logs', ['usuario_id'], unique=False)
    op.create_table('polizas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('aseguradora', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('prima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(), nullable=False),
    sa.Column('periodo_gracia_dias', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=False),
    sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('monto_comision', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_pagada', sa.Boolean(), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polizas_agente_id'), 'polizas', ['agente_id'], unique=False)
    op.create_index(op.f('ix_polizas_aseguradora'), 'polizas', ['aseguradora'], unique=False)
    op.create_index(op.f('ix_polizas_cliente_id'), 'polizas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_polizas_estatus'), 'polizas', ['estatus'], unique=False)
    op.create_index(op.f('ix_polizas_fecha_fin'), 'polizas', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_polizas_id'), 'polizas', ['id'], unique=False)
    op.create_index(op.f('ix_polizas_numero'), 'polizas', ['numero'], unique=False)
    op.create_index(op.f('ix_polizas_tipo'), 'polizas', ['tipo'], unique=False)
    op.create_table('alertas_enviadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=False),
    sa.Column('dias_antes', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=False),
    sa.Column('enviada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poliza_id'], ['polizas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_enviadas_dias_antes'), 'alertas_enviadas', ['dias_antes'], unique=False)
    op.create_index(op.f('ix_alertas_enviadas_id'), 'alertas_enviadas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_enviadas_poliza_id'), 'alertas_enviadas', ['poliza_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['polizas.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_cliente_id'), 'documentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_poliza_id'), 'documentos', ['poliza_id'], unique=False)
    op.create_index(op.f('ix_documentos_subido_por'), 'documentos', ['subido_por'], unique=False)
    op.create_index(op.f('ix_documentos_tipo'), 'documentos', ['tipo'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('completada_en', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('poliza_id', sa.Integer(), nullable=True),
    sa.Column('asignada_a', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignada_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['polizas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_asignada_a'), 'tareas', ['asignada_a'], unique=False)
    op.create_index(op.f('ix_tareas_cliente_id'), 'tareas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_tareas_completada'), 'tareas', ['completada'], unique=False)
    op.create_index(op.f('ix_tareas_fecha_vencimiento'), 'tareas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    op.create_index(op.f('ix_tareas_poliza_id'), 'tareas', ['poliza_id'], unique=False)
    op.create_index(op.f('ix_tareas_prioridad'), 'tareas', ['prioridad'], unique=False)
    op.create_index(op.f('ix_tareas_tipo'), 'tareas', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_tipo'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_prioridad'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_poliza_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_fecha_vencimiento'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_completada'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_cliente_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_asignada_a'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_documentos_tipo'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_subido_por'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_poliza_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_cliente_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_alertas_enviadas_poliza_id'), table_name='alertas_enviadas')
    op.drop_index(op.f('ix_alertas_enviadas_id'), table_name='alertas_enviadas')
    op.drop_index(op.f('ix_alertas_enviadas_dias_antes'), table_name='alertas_enviadas')
    op.drop_table('alertas_enviadas')
    op.drop_index(op.f('ix_polizas_tipo'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_numero'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_id'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_fecha_fin'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_estatus'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_cliente_id'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_aseguradora'), table_name='polizas')
    op.drop_index(op.f('ix_polizas_agente_id'), table_name='polizas')
    op.drop_table('polizas')
    op.drop_index(op.f('ix_llm_call_logs_usuario_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_proveedor'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_operacion'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index(op.f('ix_clientes_rfc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_agente_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_config_presupuestos_proveedor'), table_name='config_presupuestos')
    op.drop_index(op.f('ix_config_presupuestos_id'), table_name='config_presupuestos')
    op.drop_table('config_presupuestos')
    op.drop_index(op.f('ix_config_llm_id'), table_name='config_llm')
    op.drop_table('config_llm')
    op.drop_index(op.f('ix_config_alertas_id'), table_name='config_alertas')
    op.drop_table('config_alertas')
    # ### end Alembic commands ###
